require:
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
