require:
  - rubocop-factory_bot
  - rubocop-minitest
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

# TODO: is there a configuration that is better than disabling?
Style/GuardClause:
  Enabled: false

# TODO: is there a configuration that is better than disabling?
Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets
